-- MySQL Script generated by MySQL Workbench
-- Fri Feb 16 19:13:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema homewrks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homewrks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homewrks` DEFAULT CHARACTER SET utf8 ;
USE `homewrks` ;

-- -----------------------------------------------------
-- Table `homewrks`.`disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`disciplines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `poskey` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` CHAR NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC));


-- -----------------------------------------------------
-- Table `homewrks`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `disciplines_id` INT NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `middlename` VARCHAR(100) NULL DEFAULT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `poskey` (`firstname` ASC, `lastname` ASC),
  INDEX `fk_teachers_disciplines_idx` (`disciplines_id` ASC),
  INDEX `fk_teachers_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_teachers_disciplines`
    FOREIGN KEY (`disciplines_id`)
    REFERENCES `homewrks`.`disciplines` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_teachers_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `homewrks`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teachers_id` INT NOT NULL,
  `theme` TINYTEXT NULL,
  `task` TEXT NULL,
  `answer` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_teachers1_idx` (`teachers_id` ASC),
  CONSTRAINT `fk_tasks_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `homewrks`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teachers_id` INT NOT NULL,
  `theme` TINYTEXT NULL,
  `task` TEXT NULL,
  `option_a` TINYTEXT NULL,
  `option_b` TINYTEXT NULL,
  `option_c` TINYTEXT NULL,
  `option_d` TINYTEXT NULL,
  `answer` CHAR(1) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tests_teachers1_idx` (`teachers_id` ASC),
  CONSTRAINT `fk_tests_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `homewrks`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`materials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teachers_id` INT NOT NULL,
  `theme` TINYTEXT NULL,
  `image` TEXT NULL,
  `title` TINYTEXT NULL,
  `body` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_study_materials_teachers1_idx` (`teachers_id` ASC),
  CONSTRAINT `fk_study_materials_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `homewrks`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`works`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`works` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teachers_id` INT NOT NULL,
  `theme` TINYTEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_works_teachers1_idx` (`teachers_id` ASC),
  CONSTRAINT `fk_works_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `homewrks`.`teachers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`grades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `poskey` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`schoolkids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`schoolkids` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `grades_id` INT NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `middlename` VARCHAR(100) NULL DEFAULT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `poskey` (`firstname` ASC, `lastname` ASC),
  INDEX `fk_schoolkids_users1_idx` (`user_id` ASC),
  INDEX `fk_schoolkids_grades1_idx` (`grades_id` ASC),
  CONSTRAINT `fk_schoolkids_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `homewrks`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_schoolkids_grades1`
    FOREIGN KEY (`grades_id`)
    REFERENCES `homewrks`.`grades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`homeworks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`homeworks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `schoolkids_id` INT NOT NULL,
  `works_id` INT NOT NULL,
  `date_to_completion` DATE NOT NULL,
  `body` TEXT NULL,
  `mark` INT NULL,
  `date_of_completition` DATE NULL,
  `techer_comment` TEXT NULL,
  `teacher_mark` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_homeworks_works1_idx` (`works_id` ASC),
  INDEX `fk_homeworks_schoolkids1_idx` (`schoolkids_id` ASC),
  INDEX `date_to_completition` (`date_to_completion` ASC),
  CONSTRAINT `fk_homeworks_works1`
    FOREIGN KEY (`works_id`)
    REFERENCES `homewrks`.`works` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_homeworks_schoolkids1`
    FOREIGN KEY (`schoolkids_id`)
    REFERENCES `homewrks`.`schoolkids` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `homeworks_id` INT NOT NULL,
  `author` INT NULL,
  `body` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_homeworks1_idx` (`homeworks_id` ASC),
  CONSTRAINT `fk_comments_homeworks1`
    FOREIGN KEY (`homeworks_id`)
    REFERENCES `homewrks`.`homeworks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`blocks_of_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`blocks_of_materials` (
  `works_id` INT NOT NULL,
  `study_materials_id` INT NOT NULL,
  PRIMARY KEY (`works_id`, `study_materials_id`),
  INDEX `fk_blocks_of_materials_study_materials1_idx` (`study_materials_id` ASC),
  CONSTRAINT `fk_blocks_of_materials_works1`
    FOREIGN KEY (`works_id`)
    REFERENCES `homewrks`.`works` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_blocks_of_materials_study_materials1`
    FOREIGN KEY (`study_materials_id`)
    REFERENCES `homewrks`.`materials` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`blocks_of_tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`blocks_of_tests` (
  `works_id` INT NOT NULL,
  `tests_id` INT NOT NULL,
  PRIMARY KEY (`works_id`, `tests_id`),
  INDEX `fk_blocks_of_tests_tests1_idx` (`tests_id` ASC),
  CONSTRAINT `fk_blocks_of_tests_works1`
    FOREIGN KEY (`works_id`)
    REFERENCES `homewrks`.`works` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_blocks_of_tests_tests1`
    FOREIGN KEY (`tests_id`)
    REFERENCES `homewrks`.`tests` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`blocks_of_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`blocks_of_tasks` (
  `works_id` INT NOT NULL,
  `tasks_id` INT NOT NULL,
  PRIMARY KEY (`works_id`, `tasks_id`),
  INDEX `fk_blocks_of_tasks_tasks1_idx` (`tasks_id` ASC),
  CONSTRAINT `fk_blocks_of_tasks_works1`
    FOREIGN KEY (`works_id`)
    REFERENCES `homewrks`.`works` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_blocks_of_tasks_tasks1`
    FOREIGN KEY (`tasks_id`)
    REFERENCES `homewrks`.`tasks` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homewrks`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homewrks`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` USING BTREE (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
